### ISSUE TITLE
Create js script for this!

### ISSUE THREAD

**Issue by Superhuman07** [Superhuman07/Whatsapp-Multiple-Messenger-Bot#1]

**Comment by sagarkarira** [comment]
I already see a `scriptjs.js`. Anything that needs to be done ?

**Comment by Superhuman07** [comment]
No I just added it
Thanks anyway!

**Comment by sagarkarira** [comment]
@Superhuman07 you will not be eligible for a t-shirt if you contribute in your own repo :smiley:

**Comment by Superhuman07** [comment]
@sagarkarira thats not the case bro 
You just have to have 4 PR's atleast to get a Tee. 
I have confirmed! 😄

**Comment by sagarkarira** [comment]
@Superhuman07  Are you sure? Then everybody would get a t-shirt by making any issue and just doing it himself? Don't you think GitHub would check that?

**Comment by Superhuman07** [comment]
@sagarkarira You can visit this site to check your PR's counts for tee
https://hacktoberfestchecker.herokuapp.com/
you will get the idea!

**Comment by sagarkarira** [comment]
Wow @Superhuman07  Thanks.
